### PR TITLE
Bugfix - Data Quality

### LINKED ISSUE #223: New Class - DataQuality
Class Definition: __dataQuality__
"quality information for the data specified by a data quality scope"

Rules:
 - [ ] optional

---
Element Definitions:
 * scope: { scope } "The specific data to which the data quality information applies"
 * standaloneQualityReport: { standaloneQualityReport } "Reference to an external standalone quality report"
 * report: [ report ] "aspect of quantitative quality information"

Rules:
 - [ ] scope: required, maximum of one
 - [ ] report: required

---
mdJson:
````json
{
   "metadata": {
      "dataQuality": [
         {
            "scope": { },
            "standaloneQualityReport": { },
            "report": [ ]
         }
      ]
   }
}
````

### LINKED ISSUE #224: New Class - Report
Class Definition: __report__
"Aspect of quantitative quality information"

Rules:
 - [ ] required

---
Element Definitions:
 * type: ( enumerated ) "The type of quality report"
    * Enumerated types supported by XSD
       * DQ_AbsoluteExternalPositionalAccuracy
       * DQ_AccuracyOfATimeMeasurement
       * DQ_ConceptualConsistency
       * DQ_CompletenessCommission
       * DQ_CompletenessOmmission
       * DQ_Confidence
       * DQ_CoverageResult
       * DQ_DomainConsistency
       * DQ_FormatConsistency
       * DQ_GriddedDataPositionalAccuracy
       * DQ_Homogeneity
       * DQ_NonQuantitativeAttributeCorrectness
       * DQ_QuantitativeAttributeAccuracy
       * DQ_RelativeInternalPositionalAccuracy
       * DQ_Representativity
       * DQ_TemporalConsistency
       * DQ_TemporalValidity
       * DQ_ThematicClassisificationCorrectness
       * DQ_TopologicalConsistency
       * DQ_UsibilityElement
    * Additional enumerated types NOT supported by XSD
       * DQ_Completeness
       * DQ_LogicalConsistency
       * DQ_PositioinalAccuracy
       * DQ_TemporalQuality
 * standaloneQualityReportDetails: ( character ) "Clause in the
standaloneQualityReport where this data quality element or any related data quality element (original results in case of derivation or aggregation) is described"
 * qualityMeasure: { qualityMeasure } "Reference to measure used"
 * evaluationMethod: { evaluationMethod } "Evaluation information"
 * quantitativeResult: [ quantitativeResult ] "The values or information about the value(s) (or set of values) obtained from applying a data quality measure"
 * descriptiveResult: [ descriptiveResult ] "Data quality descriptive result"
 * conformanceResult: [ conformanceResult ] "Information about the outcome of evaluating the obtained value (or set of values) against a specified acceptable conformance quality level"
 * coverageResult: [ coverageResult ] "Result of a data quality measure organizing the measured values as a coverage"
 * derivedElementReport: [ report ] "In case of aggregation or derivation, indicates the original element"

Rules:
 - [ ] type: required
 - [ ] report: required
 - [ ] at least one result (quantitativeResult + descriptiveResult + conformanceResult + coverageResult)
 - [ ] derivedElementReport: one and only one required if type = (DQ_Confidence or DQ_Representativity or DQ_Homogeneity)

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "type": "quality report type - enumerated",
               "standaloneQualityReportDetails": "standalone details",
               "qualityMeasure": { },
               "evaluationMethod": { },
               "quantitativeResult": [ ],
               "descriptiveResult": [ ],
               "conformanceResult": [ ],
               "coverageResult": [ ],
               "derivedElementReport": [ ]
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #225: New Class - QualityMeasure
Class Definition: __qualityMeasure__
"Reference to the measure used"

Rules:
 - [ ] optional

---
Element Definitions:
 * identifier: { identifier } "Identifier of the measure, value uniquely identifying the measure within a namespace"
 * name: [ character ] "Name of the test applied to the data"
 * description: [ character ] "Description of the measure"

Rules:
 - [ ] name: required if no { identifier }

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "qualityMeasure": {
                  "identifier": { },
                  "name": ["name of measure"],
                  "description": "measure description"
               }
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #226: New Class - EvaluationMethod
Class Definition: __evaluationMethod__
"Description of the evaluation method and procedure applied"

Rules:
 - [ ] optional

---
Element Definitions:
 * type: ( enumerated ) "type of evaluation method"
    * Enumerated types supported by XSD
       * DQ_EvaluationMethod
       * DQ_DataInspection
       * DQ_AggregationDerivation
       * DQ_FullInspection
       * DQ_IndirectEvaluation
       * DQ_SampleBasedInspection
 * dateTime: [ dateTime ] "Date or range of dates on which a data quality measure was applied"
 * methodDescription: [ character ] "Description of the evaluation method"
 * evaluationProcedure: { citation } "Reference to the procedure information"
 * referenceDocument: [ citation ] "Information on documents which are referenced in developing and applying a data quality evaluation method"
 * evaluationMethodType: ( DQ_EvaluationMethodTypeCode ) "Type of method used to evaluate quality of the data"
 * deductiveSource: ( character ) "Information on which data are used as sources in deductive evaluation method"
 * samplingScheme: ( character ) "Information of the type of sampling scheme and description of the sampling procedure"
 * lotDescription: ( character ) "Information of how lots are defined"
 * samplingRatio: ( character ) "Information on how many samples on average are extracted for inspection from each lot of population"

Rules:
 - [ ] deductiveSource: required if type [ DQ_IndirectEvaluation ]
 - [ ] samplingScheme: required if type [ DQ_SampleBasedInspection ]
 - [ ] lotDescription: required if type [ DQ_SampleBasedInspection ]
 - [ ] samplingRatio: required if type [ DQ_SampleBasedInspection ]

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "evaluationMethod": {
                  "type": "evaluation method type - enumerated",
                  "dateTime": ["2019-06-11T08:35:00"],
                  "methodDescription": "evaluation method description",
                  "evaluationProcedure": { },
                  "referenceDocument": [ ],
                  "evaluationMethodType": "DQ_EvaluationMethodTypeCode",
                  "deductiveSource": "deductive source",
                  "samplingScheme": "sampling scheme",
                  "lotDescription": "lot description",
                  "samplingRatio": "sampling ratio"
               }
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #227: New Class - ConformanceResult
Class Definition: __conformanceResult__
"Information about the outcome of evaluating the obtained value (or set of values) against a specified acceptable conformance quality level"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * specification: { citation ) "Citation of data product specification or user requirement against which data are being evaluated"
 * explanation: ( character ) "Explanation of the meaning of conformance for this result"
 * pass: ( Boolean ) "Indication of the conformance result where 0 = fail and 1 = pass" default: false

Rules:
 - [ ] specification: required 
 - [ ] pass: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "conformanceResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "specification": { },
                     "explanation": "conformance result explanation",
                     "pass": false
                  }
               ]
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #228: New Class - QuantitativeResult
Class Definition: __quantitativeResult__
"The values or information about the value(s) (or set of values) obtained from applying a data quality measure"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * value: [ real ] "Quantitative value or values, content determined by the evaluation procedure used, accordingly with the value type and valueStructure defined for the measure"
 * valueUnits: ( character ) "Value unit for reporting a data quality result"
 * valueRecordType: ( character ) "Value type for reporting a data quality result, depends of the implementation"

Rules:
 - [ ] value: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "quantitativeResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "value": [9.99, 9.0],
                     "valueUnits": "value units",
                     "valueRecordType": "value record type"
                  }
               ]
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #229: New Class - DescriptiveResult
Class Definition: __descriptiveResult__
"Data quality descriptive result"

Rules:
 - [ ] optional

---
Element Definitions:
 * dateTime: [ dateTime ] "Date when the result was generated"
 * scope: { scope ) "Scope of the result"
 * statement: ( character ) "Textual expression of the descriptive result"

Rules:
 - [ ] statement: required 

---
mdJson:
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "descriptiveResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "statement": "descriptive result statement"
                  }
               ]
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #230: New Class - StandaloneQualityReport
Class Definition: __standaloneQualityReport__
"Reference to an external standalone quality report"

Rules:
 - [ ] optional

---
Element Definitions:
 * reportReference: { citation } "Reference to the associated standalone quality report"
 * abstract: ( character ) "Abstract for the associated standalone quality report"

Rules:
 - [ ] reportReference: required, maximum of one
 - [ ] abstract: required, maximum of one

---
mdJson:
````json
{
   "dataQuality": [
      {
         "standaloneQualityReport": {
            "reportReference": { },
            "abstract": "stand alone abstract"
         }
      }
   ]
}
````

### LINKED ISSUE #255: New Class - CoverageResult
Class Definition: CoverageResult
"Result of  data quality measure organizing the measured values as a coverage"

Rules:

- [ ] optional

---
Element Definitions:
 * dateTime: ( dateTime ) "Date when the result was generated"
 * scope: ( scope ) "Scope of the result"
 * spatialRepresentationType: ( spatialRepresentationType ) "Method used to spatially represent the coverage result"
 * spatialRepresentation: ( spatialRepresentation ) "Provides the digital representation of data quality measures composing the coverage result"
 * resultContent: ( rangeDimension ) "Provides the description of the content of the result coverage when the quality coverage is included with the resource being described. i.e. semantic definition of the data quality measures"
 * resourceFormat: ( format ) "Provides information about the format of the result coverage data"
 * resultFile: ( dataFile ) "Provides information about the data file containing the result coverage data"
 
Rules:
 - [ ] scope: maximum one
 - [ ] spatialRepresentationType: required, maximum one
 - [ ] spatialRepresentation: required, maximum one
 - [ ] resultContent: required if resourceFormat is null and resultFile is null
 - [ ] resourceFormat:  required if resultContent is null, maximum one
 - [ ] resultFile: required if resultContent is null, maximum one
 
---
mdJson: **See [comment below](https://github.com/adiwg/mdJson-schemas/issues/255#issuecomment-1876176119) for updated schema**
````json
{
   "dataQuality": [
      {
         "report": [
            {
               "coverageResult": [
                  {
                     "dateTime": "2019-06-11T09:00:00",
                     "scope": { },
                     "spatialRepresentationType": { },
                     "spatialRepresentation":  { },
                     "resultContent": [ ],
                     "resourceFormat": { },
                     "resultFile": { }
                  }
               ]
            }
         ]
      }
   ]
}
````

### LINKED ISSUE #256: Data Quality
This issue is a container to reference the various classes proposed as issues themselves, pertinent to implementing Data Quality as defined in ISO 19157 2013, and the 2018 Amdt.

Classes:

- [ ] adiwg/mdJSON-schemas#223
- [ ] adiwg/mdJSON-schemas#230
- [ ] adiwg/mdJSON-schemas#224
- [ ] adiwg/mdJSON-schemas#225
- [ ] adiwg/mdJSON-schemas#226
- [ ] adiwg/mdJSON-schemas#229
- [ ] adiwg/mdJSON-schemas#228
- [ ] adiwg/mdJSON-schemas#227
- [ ] adiwg/mdJSON-schemas#255
- [ ] Complete items identified in #262

### LINKED ISSUE #262: Feature/Data Quality
- [ ] Missing asterisks for required elements - review schema issues
- [ ] Missing element definitions - review schema issues
- [ ] Order of Report elements should follow that outlined in Report schema issue #224 
- [ ] Evaluation Method is not an array
- [ ] Quality Measure: either a name or identifier are required
- [ ] Translator UI not working, network error
- [ ] Type element is missing, required to identify the standard report (see issue #224)

### PR DESCRIPTION
**Pull request by jwaspin**
Closes #223 
Closes #224 
Closes #225 
Closes #226 
Closes #227 
Closes #228 
Closes #229 
Closes #230 
Closes #255 
Closes #256 
Closes #262 

# Changes

- Incremented patch version
  - package.json
  - schema/schema.json
- Updated .gitignore
- Fixed Data Quality schemas that were not correct and added missing pieces
  - Fixed the ordering of the components
  - Evaluation Method
    - object not array
    - changed dateTime to an array to handle 2 dateTime values (start & end)
  - Coverage Result
    - Modified resultContent to be resultContentDescription which is a CoverageDescription object
    - added new qualityResultFile schema
    - changed resultFile to be the qualityResultFile
    - resourceFormat changed to the format object
- Added required fields / rules
- Added descriptions
- Range element description schema cleaned up

### Testing

This version of the schema can be inspected with the schema viewer at the url below

http://23.23.4.125:8051/ (current version is 2.8.2-beta.7)

### CODE REVIEW

**Comment by jwaspin** [comment]
@dwalt & @hmaier-fws This PR is ready for review, but I'm not sure it 100% closes all those issues. I wasn't sure about a couple things like if all the scopes were required or just the top level one for data quality. Any small things I can fix immediately, but if we need some discussion on anything should we create new issues and close these ones?

One specific part to be aware of is the coverageResult class is listed in this PR, we might want to pull it out but there is an implementation for it so it might be better to create new issues to fix anything after we discuss the expected implementation (that's the one we were discussing the other day that needs to be reviewed).

**Comment by jwaspin** [comment]
Note that coverageResult has been updated and should be completed at this point. I did have to change some things based on what the schema looked like it should have been, those changes are noted in my comment followed by the modified description (which I've done in all the issues related to a new class if I had to change anything).

All of data quality should be done, so there are no known issues at this point.

**Comment by jwaspin** [comment]
In this issue: https://github.com/adiwg/mdJson-schemas/issues/262

It mentions "Translator UI not working, network error" but I'm not sure what this refers to. If I were to guess, this is actually an issue in mdTools, not mdJson-schemas, because that translator UI is not working, but there's [already an issue for that](https://github.com/adiwg/mdTools/issues/14) in the mdTools repository.

**Review by hmaier-fws — APPROVED** [review]
finally getting to this....

**Pull request merged**
